name: Publish DX.Utils to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  build:
    runs-on: ubuntu-latest
    name: build, pack & publish
    steps:      
      - uses: actions/checkout@v2
      - name: Setup .NET 6      
        uses: actions/setup-dotnet@v1        
        with:
          dotnet-version: | 
            '6.0.x'
            '7.x'
          include-prerelease: true          
      - name: add dx nuget source
        run: dotnet nuget add source ${{secrets.DX_PRIVATE_NUGET}}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -- configuration Release --no-restore
      # Publish
      - name: publish on version change        
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: DX.Utils/DX.Utils.csproj
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
